# Generated by Django 2.2.7 on 2020-02-19 09:40

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
