# Generated by Django 2.2.7 on 2020-02-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_order_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data',
        ),
    ]
